services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Root1234!
      - MSSQL_PID=Express
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - sqlserver_data:/var/opt/mssql
    expose:
      - "1433"
    user: root
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
    restart: unless-stopped

  memcached:
    image: memcached:1.6.38
    container_name: memcached
    expose:
      - "11211"
    networks:
      - app_network
    environment:
      - MEMCACHED_MEMORY=1024
      - MEMCACHED_CONNECTIONS=1024
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.17.5
    container_name: elastic_search
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    expose:
      - "9200"
    networks:
      - app_network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shareHold
    expose:
      - "8000"
    networks:
      - app_network
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - MEMCACHE_LOCATION=memcached:11211
      - DATABASE_HOST=sqlserver
    depends_on:
      sqlserver:
        condition: service_started
      memcached:
        condition: service_started
      elasticsearch:
        condition: service_started
    restart: unless-stopped

  nginx:
    image: nginx:1.27.5-alpine
    command: nginx -g 'daemon off;'
    container_name: nginx
    depends_on:
      app:
        condition: service_started
    networks:
      - app_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

volumes:
  elastic_data:
  sqlserver_data:

networks:
  app_network:
    driver: bridge