# Generated by Django 5.0 on 2025-04-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholdershistory',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('shareholder_id', models.IntegerField(blank=True, null=True)),
                ('shareholder_shares', models.FloatField(blank=True, null=True)),
                ('shareholder_percentage', models.FloatField(blank=True, null=True)),
                ('shareholder_instrument_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('shareholder_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('change', models.IntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'ShareholdersHistory',
                'managed': False,
            },
        ),
    ]
